### ISSUE TITLE
crash of v0.10.1 fatal error: concurrent map iteration and map write in sharedFilteredInformerFactory

### ISSUE THREAD

**Issue by MartinWeindel** [gardener/external-dns-management#187]
**What happened**:
after deploying v0.10.1 on canary the dns-external extension crashes on some seeds with 
```
fatal error: concurrent map iteration and map write
```

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know**:

**Environment**:

**Comment by MartinWeindel** [comment]
log of crash:

```
fatal error: concurrent map iteration and map write

goroutine 501 [running]:
runtime.throw(0x20f064b, 0x26)
        /usr/local/go/src/runtime/panic.go:1117 +0x72 fp=0xc012ee4de0 sp=0xc012ee4db0 pc=0x437132
runtime.mapiternext(0xc012ee4e78)
        /usr/local/go/src/runtime/map.go:858 +0x54c fp=0xc012ee4e60 sp=0xc012ee4de0 pc=0x410cac
github.com/gardener/controller-manager-library/pkg/resources.(*sharedFilteredInformerFactory).Start(0xc000a67a40, 0xc000be8cc0)
        /build/vendor/github.com/gardener/controller-manager-library/pkg/resources/informers.go:191 +0xa5 fp=0xc012ee4ee8 sp=0xc012ee4e60 pc=0x13472a5
github.com/gardener/controller-manager-library/pkg/informerfactories.Start(0x7f6a3cedf9f0, 0xc000579dc0, 0x7f6a3cedfa28, 0xc000a67a40, 0xc012ee4fe0, 0x1, 0x1, 0xc00086e7b0, 0x15)
        /build/vendor/github.com/gardener/controller-manager-library/pkg/informerfactories/utils.go:21 +0x49 fp=0xc012ee4f30 sp=0xc012ee4ee8 pc=0x1323329
github.com/gardener/controller-manager-library/pkg/resources.(*_i_resource).I_lookupInformer(0xc005dcb4a0, 0x0, 0xc00086e7b0, 0x15, 0x0, 0x0, 0x0, 0x0)
        /build/vendor/github.com/gardener/controller-manager-library/pkg/resources/res_internal.go:161 +0x410 fp=0xc012ee5068 sp=0xc012ee4f30 pc=0x13557f0
github.com/gardener/controller-manager-library/pkg/resources.(*_resource).getCached(0xc0035624e0, 0xc00086e7b0, 0x15, 0xc00086e7c8, 0x17, 0xc012ee5201, 0x135e4e5, 0x40a63f, 0xc00003a000)
        /build/vendor/github.com/gardener/controller-manager-library/pkg/resources/res_cached.go:19 +0x71 fp=0xc012ee5190 sp=0xc012ee5068 pc=0x1350f91
github.com/gardener/controller-manager-library/pkg/resources.(*_resource).GetCached(0xc0035624e0, 0x1f584e0, 0xc001403d20, 0x245d728, 0xc0035624e0, 0x0, 0x0)
        /build/vendor/github.com/gardener/controller-manager-library/pkg/resources/res_cached.go:70 +0xa06 fp=0xc012ee5870 sp=0xc012ee5190 pc=0x1351fe6
github.com/gardener/external-dns-management/pkg/dns/provider.(*state).registerSecret(0xc00009c640, 0x2447298, 0xc005083050, 0x7f6a3d226a18, 0xc001403d20, 0xc009e55580, 0xc000ce2901, 0x0, 0x0)


goroutine 507 [runnable]:
github.com/gardener/controller-manager-library/pkg/resources.(*Clients).GetClient(0xc00059e000, 0x0, 0x0, 0xc000cbe960, 0x2, 0x0, 0x0, 0x0, 0x0)
        /build/vendor/github.com/gardener/controller-manager-library/pkg/resources/clients.go:55 +0x12e
github.com/gardener/controller-manager-library/pkg/resources.(*structuredListWatchFactory).CreateListWatch(0xc00a3cd140, 0x242e948, 0xc000138010, 0xc001730780, 0x1e, 0x0, 0x4, 0x210a379, 0x30)
        /build/vendor/github.com/gardener/controller-manager-library/pkg/resources/listwatchfactories.go:184 +0x65
github.com/gardener/controller-manager-library/pkg/resources.(*genericInformerFactory).newInformer(0xc00a5591c0, 0x24413d8, 0xc00a3cd140, 0x3330f60, 0x0, 0x1bfc9a9, 0x6)
        /build/vendor/github.com/gardener/controller-manager-library/pkg/resources/informerfactories.go:130 +0x34e
github.com/gardener/controller-manager-library/pkg/resources.(*genericInformerFactory).informerFor(0xc00a5591c0, 0x24413d8, 0xc00a3cd140, 0x0, 0x0, 0x0, 0x0)
        /build/vendor/github.com/gardener/controller-manager-library/pkg/resources/informerfactories.go:103 +0x131
github.com/gardener/controller-manager-library/pkg/resources.(*sharedFilteredInformerFactory).lookupInformerFor(0xc000a67a40, 0x0, 0x0, 0x20b0d38, 0x2, 0x1bfc9a9, 0x6, 0xc001730780, 0x1e, 0x1f9fd00, ...)
        /build/vendor/github.com/gardener/controller-manager-library/pkg/resources/informers.go:263 +0x13b
github.com/gardener/controller-manager-library/pkg/resources.(*sharedFilteredInformerFactory).LookupInformerFor(0xc000a67a40, 0x0, 0x0, 0x20b0d38, 0x2, 0x1bfc9a9, 0x6, 0xc001730780, 0x1e, 0x203000, ...)
        /build/vendor/github.com/gardener/controller-manager-library/pkg/resources/informers.go:275 +0x70
github.com/gardener/controller-manager-library/pkg/resources.(*_i_resource).I_lookupInformer(0xc008a74450, 0x0, 0xc001730780, 0x1e, 0x0, 0x0, 0x0, 0x0)
        /build/vendor/github.com/gardener/controller-manager-library/pkg/resources/res_internal.go:157 +0x251
github.com/gardener/controller-manager-library/pkg/resources.(*_resource).getCached(0xc0034e2660, 0xc001730780, 0x1e, 0xc0005af5c0, 0x17, 0xc012eece01, 0x135e4e5, 0x40a63f, 0xc00003a000)
        /build/vendor/github.com/gardener/controller-manager-library/pkg/resources/res_cached.go:19 +0x71
github.com/gardener/controller-manager-library/pkg/resources.(*_resource).GetCached(0xc0034e2660, 0x1f584e0, 0xc000bd38a0, 0x243b7c0, 0xc000bd38a0, 0x0, 0x0)
        /build/vendor/github.com/gardener/controller-manager-library/pkg/resources/res_cached.go:70 +0xa06
github.com/gardener/controller-manager-library/pkg/resources.GetCachedSecret(0x23eb980, 0xc003d40c80, 0xc001730780, 0x1e, 0xc0005af5c0, 0x17, 0x1f584e0, 0x40a63f, 0xc00003a000)
        /build/vendor/github.com/gardener/controller-manager-library/pkg/resources/utils_secret.go:57 +0x156
github.com/gardener/controller-manager-library/pkg/resources.GetCachedSecretProperties(0x23eb980, 0xc003d40c80, 0xc001730780, 0x1e, 0xc0005af5c0, 0x17, 0x1e46620, 0x1f584e0, 0xc0005af500, 0x7f6a3d226a18)
        /build/vendor/github.com/gardener/controller-manager-library/pkg/resources/utils_secret.go:87 +0x67
github.com/gardener/controller-manager-library/pkg/resources.GetCachedSecretPropertiesByRef(...)
        /build/vendor/github.com/gardener/controller-manager-library/pkg/resources/utils_secret.go:108

```
